"""
AI provider abstraction layer.

Provides a unified interface over OpenAI (real) and a MockProvider
(for local dev / CI runs without API keys). The factory method
automatically selects the appropriate provider based on config.
"""

import asyncio
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass

import httpx

from src.config import get_settings
from src.utils.exceptions import (
    AIProviderException,
    AIQuotaExceededException,
    AITimeoutException,
)
from src.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class CompletionResult:
    text: str
    prompt_tokens: int
    completion_tokens: int
    finish_reason: str
    model: str

    @property
    def total_tokens(self) -> int:
        return self.prompt_tokens + self.completion_tokens


class BaseAIProvider(ABC):
    """Abstract provider — swap OpenAI for any other backend here."""

    @abstractmethod
    async def complete(
        self,
        messages: list[dict],
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> CompletionResult:
        ...

    @abstractmethod
    async def health_check(self) -> bool:
        ...


# ---------------------------------------------------------------------------
# OpenAI implementation
# ---------------------------------------------------------------------------

class OpenAIProvider(BaseAIProvider):
    def __init__(self):
        settings = get_settings()
        try:
            from openai import AsyncOpenAI
            self._client = AsyncOpenAI(
                api_key=settings.openai_api_key,
                timeout=30.0,
                max_retries=2,
            )
        except ImportError:
            raise RuntimeError("openai package is required. Run: pip install openai")
        self._model = settings.openai_model
        self._logger = get_logger(self.__class__.__name__)

    async def complete(
        self,
        messages: list[dict],
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> CompletionResult:
        import openai

        try:
            self._logger.info("openai.request", model=self._model, messages_count=len(messages))
            start = time.perf_counter()

            response = await self._client.chat.completions.create(
                model=self._model,
                messages=messages,
                max_tokens=max_tokens,
                temperature=temperature,
            )

            elapsed = (time.perf_counter() - start) * 1000
            self._logger.info("openai.response", latency_ms=round(elapsed, 2))

            choice = response.choices[0]
            return CompletionResult(
                text=choice.message.content or "",
                prompt_tokens=response.usage.prompt_tokens,
                completion_tokens=response.usage.completion_tokens,
                finish_reason=choice.finish_reason or "stop",
                model=response.model,
            )

        except openai.RateLimitError:
            raise AIQuotaExceededException()
        except openai.APITimeoutError:
            raise AITimeoutException(timeout_seconds=30.0)
        except openai.APIError as exc:
            raise AIProviderException(str(exc))

    async def health_check(self) -> bool:
        try:
            await self._client.models.list()
            return True
        except Exception:
            return False


# ---------------------------------------------------------------------------
# Mock provider — zero external dependencies
# ---------------------------------------------------------------------------

class MockAIProvider(BaseAIProvider):
    """
    Deterministic mock for local dev and CI.
    Responses are realistic enough for integration tests.
    """

    _MOCK_RESPONSES = {
        "summarize": (
            "This text covers several key topics in a structured manner. "
            "The author presents arguments supported by evidence, "
            "concluding with actionable recommendations for the reader."
        ),
        "classify": (
            '{"primary_category": "technical", "confidence": 0.87, '
            '"scores": {"technical": 0.87, "business": 0.08, "general": 0.05}, '
            '"reasoning": "The text contains technical terminology and discusses software concepts."}'
        ),
        "chat": (
            "That's a great question. Based on the context provided, "
            "I would approach this by first understanding the requirements, "
            "then designing a solution that balances performance and maintainability."
        ),
        "default": (
            "This is a mock response generated by the AI service. "
            "In production, this would be replaced by an actual OpenAI response "
            "based on your prompt."
        ),
    }

    async def complete(
        self,
        messages: list[dict],
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> CompletionResult:
        # Simulate realistic latency
        await asyncio.sleep(0.05)

        last_content = messages[-1].get("content", "").lower()

        if "summarize" in last_content or "summary" in last_content:
            text = self._MOCK_RESPONSES["summarize"]
        elif "classify" in last_content or "category" in last_content:
            text = self._MOCK_RESPONSES["classify"]
        elif len(messages) > 1:
            text = self._MOCK_RESPONSES["chat"]
        else:
            text = self._MOCK_RESPONSES["default"]

        word_count = len(text.split())
        return CompletionResult(
            text=text,
            prompt_tokens=sum(len(m.get("content", "").split()) for m in messages),
            completion_tokens=word_count,
            finish_reason="stop",
            model="mock-gpt-3.5-turbo",
        )

    async def health_check(self) -> bool:
        return True


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def get_ai_provider() -> BaseAIProvider:
    """
    Returns the appropriate AI provider based on configuration.
    Falls back to MockProvider when OPENAI_API_KEY is not set.
    """
    settings = get_settings()
    if settings.openai_api_key and settings.openai_api_key not in ("mock-key", "your-openai-api-key-here"):
        logger.info("ai.provider.selected", provider="openai")
        return OpenAIProvider()
    logger.warning("ai.provider.selected", provider="mock", reason="OPENAI_API_KEY not configured")
    return MockAIProvider()
